### ISSUE TITLE
NullPointerException thrown if export destination is invalid

### ISSUE THREAD

**Issue by Aurelien74** [oxfordinternetinstitute/gephi-plugins#10]
Hi,

When I try to export any of my projects, I've always the same error:
"java.lang.NullPointerException".
I run Gephi 0.8.2 with 64bits java jdk and -J-Xms256m -J-Xmx10000m parameters. When I switch to 32 bits, the error still remain.

Thanks for your help!

**Comment by computermacgyver** [comment]
Thanks for reporting this and apologies for the trouble. I expect this has something to do when not all the node properties I expect to be present are there. Is there a small, example dataset on which this error occurs that you would be willing to share (privately by email with me is fine [vis@oii.ox.ac.uk]). Otherwise, could you tell me if any of the following is missing in your network:
- Node color
- Node label
- Edge weight
  ?

Thanks!

**Comment by Aurelien74** [comment]
Hi,

This error occur even with some basic generated graph. And of course color is missing. What is the syntax exactly?

Thanks for your help!

**Comment by vincentkollebolle** [comment]
A NPE exception is egally thrown if you don't specify a good path for the export.

**Comment by computermacgyver** [comment]
Thanks, Vincent, you're absolutely right. I've just fixed that error now.
