### ISSUE TITLE
delete nodes after export?

### ISSUE THREAD

**Issue by hdean83** [oxfordinternetinstitute/gephi-plugins#24]
Hi - I have developed some good exports, and would rather not recreate the wheel.  I just need to delete three nodes from a series of exported files, and wondering if I can do that through the sigma.js code, or whether I have to recreate and re-export the graphs in gephi.

**Comment by computermacgyver** [comment]
Hi,

There are a few options aside from a full re-create:
1) If you have the network saved in another format (Gephi, GraphML, gexf, etc.) you could re-open it in Gephi, export it to a new location and then just copy the data.json file from the new export to your previous export. This way you don't have to worry about recreating any of the other properties or any other custom layout  you have done.

2) If you don't mind getting your hands dirty with Python or similar, you can load the data.json file and remove the nodes from the file. You also need to remove the edges that connect to these nodes or sigma.js will complain (this is why I suggest using a scripting language to edit the file rather than doing it by hand)

3) Finally, a ugly but effective method would be to edit the sigma.parseJson.js file to either (a) not add the nodes/edges or (b) add everything but then to remove the nodes.

Let me know if the first option will work for you, which is probably the nicest. If not, let me know if you'd like further explanation of the either of the other two options.

**Comment by hdean83** [comment]
Hi - I tried out the first option -with one of the graphs.  It works
great.  The only issue is that there is now a gap in the visualization
layout where the nodes that I deleted were once housed (the layout is
radial axis).  However, it is a good enough fix for now - the main concern
was that these nodes should not be included in the network maps.  That
being said, if you have a suggestion on how to amend the layout so that the
gap is not apparent in the visual layout, that would be much appreciated.

Thanks so much for your help!!! Life Saver.

On Tue, Jul 2, 2013 at 5:24 PM, computermacgyver
notifications@github.comwrote:

> Hi,
> 
> There are a few options aside from a full re-create:
> 1) If you have the network saved in another format (Gephi, GraphML, gexf,
> etc.) you could re-open it in Gephi, export it to a new location and then
> just copy the data.json file from the new export to your previous export.
> This way you don't have to worry about recreating any of the other
> properties or any other custom layout you have done.
> 
> 2) If you don't mind getting your hands dirty with Python or similar, you
> can load the data.json file and remove the nodes from the file. You also
> need to remove the edges that connect to these nodes or sigma.js will
> complain (this is why I suggest using a scripting language to edit the file
> rather than doing it by hand)
> 
> 3) Finally, a ugly but effective method would be to edit the
> sigma.parseJson.js file to either (a) not add the nodes/edges or (b) add
> everything but then to remove the nodes.
> 
> Let me know if the first option will work for you, which is probably the
> nicest. If not, let me know if you'd like further explanation of the either
> of the other two options.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/oxfordinternetinstitute/gephi-plugins/issues/24#issuecomment-20377428
> .

## 

Hannah Dean
Department of Environmental, Earth and Ocean Sciences (EEOS)
University of Massachusetts Boston
100 Morrissey Blvd.
Boston, MA 02125-3393, USA
