### ISSUE TITLE
Put a list on Information Pane

### ISSUE THREAD

**Issue by nurendahs** [oxfordinternetinstitute/gephi-plugins#46]
Hi, I want to make my data into list in Information Pane (like some explanation about my nodes into list <li></li>). But I don't know where to edited it.  In index.html it just showed the main content <div class="data"></div>. Do you know what file should I edited? Thanks

**Comment by computermacgyver** [comment]
I'm not sure I understand your question. The data for the information pane is loaded from the data.json file by JavaScript in main.js. The best/easiest way to edit the data for a particular node is to adjust the attributes for that node. If you create a String column for nodes in the Data laboratory tab of Gephi, you can fill this with whatever information you want. You can also put html into this field to control the formatting if you want a bulleted list or whatever.

**Comment by nurendahs** [comment]
Yes, I understand. I mean I want to control my formatting like this:
Information:
Blabla
Blablabla
Blablabla

I dont't know where to edit or add the code. Usually I edit in html like this:

![capture](https://cloud.githubusercontent.com/assets/4320461/3113396/b2f388b0-e6d6-11e3-909d-a34408cc019e.PNG)

In index.html just showed 
![capture2](https://cloud.githubusercontent.com/assets/4320461/3113398/e5e22c68-e6d6-11e3-8bcb-5118cd1ce580.PNG)
I still confuse... How can I put html to control the formatting? :/

**Comment by computermacgyver** [comment]
And to clarify is this for the panel on the left that lists the title of
the visualization, has the search box, etc. or for the panel on the right
that lists the information about a clicked node?

**Comment by nurendahs** [comment]
It's for the right panel that list the description about clicked node. I want to put it above the "connections".

**Comment by computermacgyver** [comment]
Got you. The email alert didn't have the picture in your earlier post, which makes it clear.

The data div is populated via [JavaScript in the main.js file](https://github.com/oxfordinternetinstitute/InteractiveVis/blob/master/network/js/main.js#L602)

It loads in all the attributes for a given node from the data.json file. If goal is simply to change the formatting so that all attributes are in a bulleted list, then you would just have to change the JavaScript code at the line (or slightly above) linked above. 

If the goal is to adjust the display of one particular attribute then it is probably easier to edit that attribute in Gephi with the html markup in Gephi and then re-export.

**Comment by nurendahs** [comment]
Hmm... Actually I'm not good in Javascript. And I confused about commas and spaces in my atrribute. There's a space in my attribute, and I want to replace comma with bulleted list . So this must be like this:

From this
Description:
Color - White,Eyes - Black 

Into this:
Description:
Color-White
Eyes-Black 

I just don't know the code. I'm newbie on this one. Sorry for asking to much ._.

**Comment by computermacgyver** [comment]
This is obviously quite specific, but I think the best thing to do would be to edit the data.json file to reformat this attribute. If your data.json file is online somewhere or you can email it to me (use the contact form on my website) I can probably help.
