### ISSUE TITLE
Label font size doesn't change with "defaultLabelSize" in config.json

### ISSUE THREAD

**Issue by a10martin** [oxfordinternetinstitute/gephi-plugins#50]
I've looked through sigma.js, main.js, even the CSS files, and have read up on sigma.js trying to understand this behavior, and can't track down what's going on. 

In config.json, I can separately change the drawing properties for labels and for labels-on-hover. For instance, "defaultLabelColor" and "defaultLabelHoverColor" can be set to different values, and the graph will load with those different colors. When the graph loads, I'll see some labels (according to my "labelThreshold" settings) with defaultLabelColor, and then if I hover over a node, I'll see the defaultLabelHoverColor.

But I can't change the label font _size_ in the same way. In fact, I can't increase the size of non-hovered labels at all. If I change "defaultLabelSize" it will change the font size of hovered labels, but when I load the graph itself, the node labels are too small to read no matter what I do (of course, I can increase size with Ctrl+, but I'd like users to be able to read the graph when it first loads).

OII's UK central government websites example shows this pretty well: http://oxfordinternetinstitute.github.io/InteractiveVis/network/index.html?config=config_ukgov.json -- on load, the label for the big red central point, direct.gov.uk, is quite small; none of the config.json options seem to respond to the property that draws these labels rather than the hovered labels.

**Comment by jthrilly** [comment]
Thanks for reporting the issue.

Unfortunately sigma.js has moved on significantly since we worked on this project, and a lack of time and resources mean that we haven't been able to update it. The documentation that is online now uses a completely rewritten API. The other bad news is that the version of sigma we built this on was notorious for its inconsistencies and quirks. I seem to recall that the 'defaultLabelSize' in particular didn't behave how one might expect. 

You seem to be comfortable hacking around with the JS, so my advice would be to try to build your own interface based on the newest sigma version. The functionality we added (searching and group select) is pretty trivial to implement, so I think some modest effort could get it done.

Sorry to not be able to offer more help than that...

**Comment by triplingual** [comment]
Old thread, but if anyone else is reading this, I found that blanking the value for `fontStyle` in `config.json` then made it possible for me to change `defaultLabelSize` and have an effect.

Pertinent JSON fragment, with pseudo-comments:
https://gist.github.com/triplingual/9b8fd0e4d1efdc66204e2cc9389a764a

**Comment by computermacgyver** [comment]
Thanks, @triplingual . A new version of the plugin with the latest version of sigma is [in the works](http://www.github.com/oii-nexus/examples). Moving to the latest version of sigma should solve this and a few other issues, but until that work is complete this is a great workaround. Thanks.

**Comment by computermacgyver** [comment]
I know this is an old thread, but since this popped back up in more recent development work, I have traced it to a missing space in Sigma. Blanking the value for fontStyle as triplingual suggests works; or, the alternative is simply to add a trailing space (i.e., change "bold" to "bold ").
