### ISSUE TITLE
File->export->sigma.js template

### ISSUE THREAD

**Issue by mindlessrabble** [oxfordinternetinstitute/gephi-plugins#57]
I was able to successfully install the Sigma.js exporter plugin to Gephi 0.9  successfully.  But after clicking there it does not give any dialog for selecting the file name or location.

**Comment by computermacgyver** [comment]
Due to fundamental changes to the architecture of Gephi, simply installing the old version will not work. The JSONExporter plugin has been rewritten and sigma.js will be re-written as well. The plugin architecture was just finalized this month by the Gephi team; so, you will have to wait a little longer for the new versions to be completed.
