### ISSUE TITLE
Is it possible to have edge weight reflected in the output?

### ISSUE THREAD

**Issue by birdsarah** [oxfordinternetinstitute/gephi-plugins#9]

**Comment by computermacgyver** [comment]
Thanks for asking. Since the 21  Feb update to the plugin, edge weight is stored in the data file --- I have not been able to find a way to set sensible defaults for the minEdgeSize and maxEdgeSize parameters that work in all cases. For now, (a) make sure you have the latest version of the plugin , (b) generate your graph as usual, (c) after generation open the config.json file in any text editor (e.g. notepad) and look for the maxEdgeSize parameter. Try changing this to a larger value and inspecting the results to find a value that works for the your particular graph.

I aim to create a way to better adjust these parameters in the future. Please let me know if this helps.

Another possibility would be also reflect the edge weight of the connected nodes in the right side panel that is shown after  clicking on a node. Would this be helpful?

**Comment by birdsarah** [comment]
Thanks for the quick response!  Changing the minEdgeSize & maxEdgeSize worked great for me.

Adding the edge weight to the side panel would also be good, but not necessary for me in this case.

**Comment by schignel** [comment]
Hi @computermacgyver and @birdsarah, I am trying to show the edgeweights on my graph by adjusting the mid and max edge size parameters but they do not appear to be changing. 

Below is with maxEdgeSize=10 and minEdgeSize=0.2
Do you have any suggestions? Thanks!

![sigma js_maxedgesize 10_minedgesize 0 2](https://user-images.githubusercontent.com/19474876/34377525-4c708d58-eb56-11e7-8a20-23a232f62a29.PNG)

**Comment by computermacgyver** [comment]
Hi @schignel . Can you please send me your data.json and config.json files so that I can look into this? You can send me an [email via my website](http://www.scotthale.net/blog/?page_id=9), which I reply to and you can then attach files if you'd like to avoid posting them publicly.

Cheers,
Scott
